### ISSUE TITLE
無法替換字體

### ISSUE THREAD

**Issue by zacaoX** [ysc3839/FontMod#29]
tg ver 1.5.12

[LoadUserFonts] FindFirstFile failed! (3)
[DllMain] SystemParametersInfo NONCLIENTMETRICS.lfMessageFont.lfFaceName="Microsoft YaHei UI"

**Comment by ysc3839** [comment]
请问是否使用了 MacTypes，已经有不兼容的案例。

**Comment by gadfly3173** [comment]
> 请问是否使用了 MacType，已经有不兼容的案例。

请问有办法同时使用么

**Comment by ysc3839** [comment]
@gadfly3173 MacType 有提供修改字体的功能吗？如果有的话就不需要使用了。我暂时也不知道解决方法，这个项目主要是针对不使用 MacType 的用户。

**Comment by tsingbinjung** [comment]
实测Telegram Desktop 移动版（1.8.1）和Mactype（beta 6）可以兼容，中英文字体（系统是英语）都可以自定义

**Comment by auxford** [comment]
Telegram Desktop Portable 和 MacType ( Registry Mode ) 可以兼容，中英文字体都可自定义

**Comment by TsXcd** [comment]
> Telegram Desktop Portable 和 MacType ( Registry Mode ) 可以兼容，中英文字体都可自定义

可惜我的使用场景是独立模式，不知是否有解决方案？
目前只能暂且在Mactype中将Telegram排除渲染来兼容使用。😥

**Comment by hosxy** [comment]
> 
> 
> > Telegram Desktop Portable 和 MacType ( Registry Mode ) 可以兼容，中英文字体都可自定义
> 
> 可惜我的使用场景是独立模式，不知是否有解决方案？
> 目前只能暂且在Mactype中将Telegram排除渲染来兼容使用。😥


可以尝试关掉FontMod，并使用Mactype对Telegram进行单独设置，比如：
```
[FontSubstitutes@Telegram.exe]
SimSun=Microsoft YaHei UI
@SimSun=@Microsoft YaHei UI
NSimSun=Microsoft YaHei UI
@NSimSun=@Microsoft YaHei UI
PMingLiU=Microsoft YaHei UI
@PMingLiU=@Microsoft YaHei UI
MS UI Gothic=Microsoft YaHei UI
@MS UI Gothic=@Microsoft YaHei UI
Gulim=Microsoft YaHei UI
@Gulim=@Microsoft YaHei UI
Open Sans=Microsoft YaHei UI
@Open Sans=@Microsoft YaHei UI
```
