### ISSUE TITLE
Windows Defender 报毒 (Trojan:Win32/Fuery.A!cl)

### ISSUE THREAD

**Issue by tobyxdd** [ysc3839/FontMod#32]
![image](https://user-images.githubusercontent.com/1414953/57174311-7da68100-6e6f-11e9-944d-cc317b9a7330.png)

同样的 DLL 从今天开始突然就报毒了... 从 Release 重新下载依然如此 不过我相信肯定是误报

**Comment by ysc3839** [comment]
这是误报，我无法解决。这也是我开源的原因，如果真的担心有病毒可以自行检查源代码然后编译。
