### ISSUE TITLE
最新的 dll 文件被 windows defender 判定为病毒

### ISSUE THREAD

**Issue by nikzhang2016** [ysc3839/FontMod#35]
系统版本：windows 10 1809 x64
报毒软件：windows defender
报告信息如下：
```
Program:Win32/Unwaders.A!ml
警报级别：严重
状态：已隔离
类别：潜在的垃圾软件
详细信息：这个程序具有可能有害的行为。
受影响的项目:
file: C:\Telegram\winmm.dll
```

**Comment by ysc3839** [comment]
之前已经有过[类似案例](https://github.com/ysc3839/FontMod/issues/32#issuecomment-490178630)，我无法解决此问题。
