### ISSUE TITLE
默认是不是不替换英文字体？

### ISSUE THREAD

**Issue by hosxy** [ysc3839/FontMod#38]
请问怎么设置才能把英文字体也替换掉？
主要是因为我使用的 `更纱黑体 UI SC Medium` 替换宋体的，如果不一同替换英文字体，会导致中英文字体粗细不一致，很不谐调

**Comment by ysc3839** [comment]
替换 `OpenSans` 字体，具体有哪些字体请开启 debug 后查看日志。
