### ISSUE TITLE
Windows Defender diagnoses it a virus

### ISSUE THREAD

**Issue by ComputerPark** [ysc3839/FontMod#39]
![Annotation 2019-09-23 192550](https://user-images.githubusercontent.com/30792695/65418703-fcf51b00-de37-11e9-99de-01d618c01635.png)

As you can see in the picture above, Windows Defender diagnoses it a virus.

**Comment by ysc3839** [comment]
This is an known issue, which is reported by other users some times ago. Because FontMod uses DLL hijack and hook, it may be reported as a virus. I can't fix this issue.
