### ISSUE TITLE
winmm.dll被defender報毒，無法打開tg

### ISSUE THREAD

**Issue by zacaoX** [ysc3839/FontMod#40]
另外tg無法啓動，必須移除winmm.dll

**Comment by bestpika** [comment]
false positive.

**Comment by ysc3839** [comment]
这是一个已知问题，之前也被其他用户报告过。因为 FontMod 使用 DLL 劫持和 Hook 技术，所以有可能被报告为病毒。我无法解决这个问题。

**Comment by bestpika** [comment]
@ysc3839 其實你有辦法解決，只要去[這裡](https://www.microsoft.com/en-us/wdsi/filesubmission)回報誤報就好了，那天我看到就上去報了一下，然後發現其實他早就解掉了只差定義檔還沒更新而已
