### ISSUE TITLE
运行程序后没有创建 FontMod.yaml

### ISSUE THREAD

**Issue by Kawaii-KM** [ysc3839/FontMod#52]
Windows 7 SP1
Telegram Desktop 1.9.14
把dll放在 Telegram.exe 的目录里，打开 Telegram，字体没有改变，目录也没有创建 FontMod.yaml

**Comment by ysc3839** [comment]
可能是没有写入权限？

**Comment by Kawaii-KM** [comment]
所以说应该怎么做？

**Comment by ysc3839** [comment]
修改文件夹权限，允许写入。

**Comment by Kawaii-KM** [comment]
管理员授权了，还是不行

**Comment by ysc3839** [comment]
那我也不知道是什么问题了。我目前使用 Windows 10 x64 Version 1909 是没有问题的。

**Comment by liamhui** [comment]
我用了，很好用，感谢作者

**Comment by wuhang2003** [comment]
同 Windows 7 SP1 x64，版本 1.9.19 ，按照上面的操作，同样无法新建 FontMod.yaml
