### ISSUE TITLE
Telegram 运行程序后无法新建 FontMod.yaml

### ISSUE THREAD

**Issue by wuhang2003** [ysc3839/FontMod#53]
和 [#52](https://github.com/ysc3839/FontMod/issues/52) 一样，Windows 7 SP1 x64，Telegram 版本 1.9.19 ，按照教程操作，无法新建 FontMod.yaml
（怀疑是不是与 Windows 7 的一些机制有问题

**Comment by dmcdark** [comment]
Win10，Telegram 1.9.21 用不了。手动创建 FontMod.yaml也用不了

**Comment by wuhang2003** [comment]
@ysc3839 来研究一下问题

**Comment by ysc3839** [comment]
@wuhang2003 我已经在 #52 中说过了可能的解决方案，如果仍然无效我也不知道是什么问题了。
@dmcdark 我自己在 Win10 下配合 Telegram 使用是没有问题的。

**Comment by dmcdark** [comment]
> @wuhang2003 我已经在 #52 中说过了可能的解决方案，如果仍然无效我也不知道是什么问题了。
> @dmcdark 我自己在 Win10 下配合 Telegram 使用是没有问题的。

有说字体文件要是ttf吗？我是复制系统的ttc文件

**Comment by ysc3839** [comment]
@dmcdark
不管字体是否支持，FontMod 正常加载之后都会创建配置文件的。

**Comment by dmcdark** [comment]
> @dmcdark
> 不管字体是否支持，FontMod 正常加载之后都会创建配置文件的。

我这就是不创建配置文件…但是有log…算了吧，谢谢你的回复
