### ISSUE TITLE
Telegram 1.9.21 没效果？

### ISSUE THREAD

**Issue by rampageX** [ysc3839/FontMod#55]
系统是 Windows 10 x64 1909, 之前也没用过，直接改名 winmm.dll 放到 Telegram.exe 同目录下，重启 Telegram 没效果，目录下也没有自动生成 FontMod.yaml 这个文件。

**Comment by ysc3839** [comment]
我这里 Telegram 1.9.21 是没有问题的，系统是 Windows 10 Pro x64 Version 1909。

**Comment by rampageX** [comment]
这和我使用的是便携版 Portable 版本有关系吗？

**Comment by ysc3839** [comment]
应该是没有的。

**Comment by rampageX** [comment]
我的问题找到了，通过用 `Process Hacker | Modules` 对比可行的机器以及不可行的机器：

1. 可行的机器成功载入了 `telegram.exe` 目录下的 `winmm.dll`，不可行机器没有载入；
2. 不可行机器载入了 `AcGenral.dll AcLayers.dll` 这两个与 `Program Compatibility Assistant Service` 服务相关的 dll；
3. 右键点击 telegram.exe，发现 `兼容性-设置` 选项选中了 `禁用全屏优化` 选项，去掉，还是不行；
4. 重启后发现 `禁用全屏优化` 又被自动选上，`AcGenral.dll AcLayers.dll` 被载入；
5. 卸载前几天安装的 `automatically_disable_fullscreen_optimizations.bat` 自动禁用全屏优化脚本所做的系统更改（Clear，Uninstall），重启，启动 telegram.exe 更改字体成功。

结论是本注入方式与 `应用程序兼容助手` 某些选项可能有冲突。

**Comment by ysc3839** [comment]
@rampageX 感谢你的测试！
