### ISSUE TITLE
Windows XP support? "Application failed to initialize properly"

### ISSUE THREAD

**Issue by jocap** [ysc3839/FontMod#57]
On Windows XP, Telegram does not work with FontMod. The following error is displayed:

> The application failed to initialize properly (0xc0000142). Click on OK to terminate the application.

Maybe this is because FontMod.dll is not compiled for Windows XP? I would be very thankful if you could make it work for Windows XP.

**Comment by ysc3839** [comment]
Maybe it's fixed in [v2.1](https://github.com/ysc3839/FontMod/releases/tag/v2.1). Can you help me test it?
