### ISSUE TITLE
support LINE?

### ISSUE THREAD

**Issue by roytam1** [ysc3839/FontMod#60]
LINE Desktop version is also written in Qt5, but it detects DLL injection:
![image](https://user-images.githubusercontent.com/1192577/81430979-fa5ef000-9192-11ea-993b-7a36b9e31b54.png)

**Comment by ysc3839** [comment]
I won't implement application-specific feature in FontMod. Instead, I will provide a "DLL loader" feature, which allows you load your own DLL. Then anyone can write a patch for an application.

**Comment by ysc3839** [comment]
Fixed in [v2.1](https://github.com/ysc3839/FontMod/releases/tag/v2.1), please rename to `d3d9.dll`.
![image](https://user-images.githubusercontent.com/12028138/86812961-32f74900-c0b2-11ea-8658-8d38df490247.png)
