### ISSUE TITLE
[Question] How to use the overridings ?

### ISSUE THREAD

**Issue by M299792458** [ysc3839/FontMod#67]
Hello @ysc3839, thanks for this wonderful tool. :+1: 
I'm a non coder, I'm just a regular user. I would like know to how to use these overridings ? **it doesn't work as said here: _Remove '#' to override font style_**.
of course the Mod is perfectly working on the latest version of Telegram Desktop (2.4.4), just this override thing, it doesn't work. :( 
Can you please show me how ? write me an example please.
Thanks in advance.

(_Remove '#' to override font style
size: 0
width: 0
weight: 0
italic: false
underLine: false
strikeOut: false
charSet: 0
outPrecision: 0
clipPrecision: 0
quality: 0
pitchAndFamily: 0_)

**Comment by ysc3839** [comment]
What's your full config file?

**Comment by M299792458** [comment]
[FontMod.yaml.txt](https://github.com/ysc3839/FontMod/files/5444793/FontMod.yaml.txt)

_(I've just added .txt extension because GitHub refused to upload it in .yaml extension.)_

**Comment by ysc3839** [comment]
The `style: &style` is duplicated in your config. Keep only one.
And if you want to change size, just remove the '#' before the size.
For example, before is `# size: 0`, after is `size: 20` (20 is the size number).

**Comment by M299792458** [comment]
> The `style: &style` is duplicated in your config. Keep only one.
> And if you want to change size, just remove the '#' before the size.
> For example, before is `# size: 0`, after is `size: 20` (20 is the size number).

Thank you very much. Can't we make it for only one font ? Like, for example, if I want to change the size of this:
```
  DAOpenSansRegular:
    replace: Segoe UI
    <<: *style
```
Can't I ?

**Comment by ysc3839** [comment]
> Can't we make it for only one font?

You can. Just write the size in that font.
For example:
```
  DAOpenSansRegular:
    replace: Segoe UI
    size: 20
```

**Comment by ysc3839** [comment]
The `<<: *style` just like copy paste the contents of style into the font.

**Comment by M299792458** [comment]
Thanks. :)
I shall close this now.
