### ISSUE TITLE
[Feature Request] Support GDI+

### ISSUE THREAD

**Issue by saftle** [ysc3839/FontMod#68]
I managed to successfully inject a font in Final Fantasy III, but not Final Fantasy V on Steam. The applications seems to be a QT application, so I'm not sure what the issue is.

I also tried disabling fullscreen optimations with the dll named winmm.dll, however nothing would show up in the debug log then, so I renamed it to version.dll. Now data is shown in the log even with fullscreen optimizations disabled. Still no luck though replacing any fonts.

Any help would be greatly appreciated! Here is my yaml and debug log:

FontMod.yaml:
```
style: &style
# Remove '#' to override font style
#  size: 0
#  width: 0
#  weight: 0
#  italic: true
#  underLine: true
#  strikeOut: false
#  charSet: 0
#  outPrecision: 0
#  clipPrecision: 0
#  quality: 0
#  pitchAndFamily: 0

fonts:
  Segoe UI: &ff5-font # English
    replace: Comic Sans MS
    <<: *style
  MS Gothic UI:
    replace: Comic Sans MS
    <<: *style
  MS UI Gothic:
    replace: Comic Sans MS
    <<: *style
  Sans Serif:
    replace: Comic Sans MS
    <<: *style
  Segoe UI Light: *ff5-font
  Segoe UI Light Italic: *ff5-font
  Segoe UI Semilight: *ff5-font
  Segoe UI Semilight Italic: *ff5-font
  Segoe UI Italic: *ff5-font
  Segoe UI Semibold: *ff5-font
  Segoe UI Semibold Italic: *ff5-font
  Segoe UI Bold: *ff5-font
  Segoe UI Bold Italic: *ff5-font
  Segoe UI Black: *ff5-font
  Segoe UI Black Italic: *ff5-font

fixGSOFont: true # true is to use system UI font
#fixGSOFont: *ff5-font # Or replace with user defined font
debug: false
```
FontMod.log:
```
[DllMain] SystemParametersInfo NONCLIENTMETRICS.lfMessageFont.lfFaceName="Segoe UI"
[CreateFont] name = "Segoe UI", height = -15, width = 0, escapement = 0, orientation = 0, weight = 400, italic = false, underline = false, strikeout = false, charset = 1, outprecision = 0, clipprecision = 0, quality = 0, pitchandfamily = 0
[CreateFont] name = "Segoe UI", height = -15, width = 0, escapement = 0, orientation = 0, weight = 400, italic = false, underline = false, strikeout = false, charset = 1, outprecision = 0, clipprecision = 0, quality = 0, pitchandfamily = 0
[DllMain] SystemParametersInfo NONCLIENTMETRICS.lfMessageFont.lfFaceName="Segoe UI"
[CreateFont] name = "Segoe UI", height = -15, width = 0, escapement = 0, orientation = 0, weight = 400, italic = false, underline = false, strikeout = false, charset = 1, outprecision = 0, clipprecision = 0, quality = 0, pitchandfamily = 0
[CreateFont] name = "Segoe UI", height = -15, width = 0, escapement = 0, orientation = 0, weight = 400, italic = false, underline = false, strikeout = false, charset = 1, outprecision = 0, clipprecision = 0, quality = 0, pitchandfamily = 0
[CreateFont] name = "Segoe UI", height = -15, width = 0, escapement = 0, orientation = 0, weight = 400, italic = false, underline = false, strikeout = false, charset = 1, outprecision = 0, clipprecision = 0, quality = 0, pitchandfamily = 0
[CreateFont] name = "Segoe UI", height = -15, width = 0, escapement = 0, orientation = 0, weight = 400, italic = false, underline = false, strikeout = false, charset = 1, outprecision = 0, clipprecision = 0, quality = 0, pitchandfamily = 0
[CreateFont] name = "Segoe UI", height = -15, width = 0, escapement = 0, orientation = 0, weight = 400, italic = false, underline = false, strikeout = false, charset = 1, outprecision = 0, clipprecision = 0, quality = 0, pitchandfamily = 0
[CreateFont] name = "Segoe UI", height = -15, width = 0, escapement = 0, orientation = 0, weight = 400, italic = false, underline = false, strikeout = false, charset = 1, outprecision = 0, clipprecision = 0, quality = 0, pitchandfamily = 0
```

**Comment by ysc3839** [comment]
Maybe the game is not using GDI font. In my memory, many games using it's own font system instead of operating system's.
While FontMod supports only GDI font, it doesn't work with a game not using GDI font.

Another possible issue is that FontMod is loaded too late. Maybe the game has finished loading fonts before FontMod being loaded into the game process.

Both situation requires you using some debugging tools to check. Unfortunately I don't have this game, so I can't check it.
(I can use a priated version game. But I think it's not good.)

**Comment by saftle** [comment]
Thank you so much for responding! The game does appear to load GDI fonts, based on what I've found using a hex editor.

I'd love to buy the game for you on Steam. Add me on Steam, and I'll grab it. https://steamcommunity.com/id/saftle/. It would be the least I could do.

**Comment by ysc3839** [comment]
@saftle You don't need to buy the game for me, I think it's expensive. I can wait for a discount and buy it.

**Comment by saftle** [comment]
Well, I would hate for you to buy it, since the game on its own is broken in a lot of ways. I am a part of a modding community where we are trying to fix up a bunch of games and wanted to use your mod to fix the font when rendering the game at its native resolution of 640x384 (and upscaled with https://github.com/mashakos/OmniScaler/). The font would be great to replace anyways, but also it smashes together at the native resolution.

I don't mind grabbing it for you at all in order to invest in a possible fix (even if it isn't possible) :)

**Comment by saftle** [comment]
Good news. We have more information now. A modder in our discord found out that the game actually uses GDI+ and not GDI. They said that the fontmod currently doesn't support GDI+, which is why it doesn't work in the game. Is GDI+ planned in the future?

**Comment by ysc3839** [comment]
After some testing I found GDI+ is not using GDI font on Win10. Looks like it's using DirectWrite.

**Comment by ysc3839** [comment]
After some investigate, I think it's not easy to fully support GDI+.

When using GDI+ to render text:
1. Create a font family by it's name. (GdipCreateFontFamilyFromName)
2. Create a font using font family, size and style. (GdipCreateFont)
3. Render text using that font.

I can't get the name and style in the same function, so I have to keep track of the font family pointer -> font name relation. However the font family can be copied, so the relation would be incomplete.
Another solution is to get font family name (GdipGetFamilyName) every time before font created and check if it match rules, but I think it's inefficient.

**Comment by zqdalianchina** [comment]
{ "fonts": 
    { "SimSun": 
        { "replace": 
            "HarmonyOS Sans SC", 
            "#size": 0, 
            "#width": 0, 
            "#weight": 0, 
            "#italic": false, 
            "#underLine": false, 
            "#strikeOut": false 
        }, 

        "Open Sans": { 
            "replace": "HarmonyOS Sans SC", 
            "#size": 0, 
            "#width": 0, 
            "#weight": 0, 
            "#italic": false, 
            "#underLine": false, 
            "#strikeOut": false 
        }, 
        "Open Sans Semibold": { 
            "replace": "HarmonyOS Sans SC", 
            "#size": 0, 
            "#width": 0, 
            "#weight": 0, 
            "#italic": false, 
            "#underLine": false, 
            "#strikeOut": false 
        }, 
        "Arial": { 
            "replace": "HarmonyOS Sans SC", 
            "#size": 0, 
            "#width": 0, 
            "#weight": 0, 
            "#italic": false, 
            "#underLine": false, 
            "#strikeOut": false 
        } 
    }, 
    "debug": false 
}

**Comment by zqdalianchina** [comment]
{ "fonts": 
    { "SimSun": 
        { "replace": 
            "HarmonyOS Sans SC", 
            "#size": 0, 
            "#width": 0, 
            "#weight": 0, 
            "#italic": false, 
            "#underLine": false, 
            "#strikeOut": false 
        }, 

        "Open Sans": { 
            "replace": "HarmonyOS Sans SC", 
            "#size": 0, 
            "#width": 0, 
            "#weight": 0, 
            "#italic": false, 
            "#underLine": false, 
            "#strikeOut": false 
        }, 
        "Open Sans Semibold": { 
            "replace": "HarmonyOS Sans SC", 
            "#size": 0, 
            "#width": 0, 
            "#weight": 0, 
            "#italic": false, 
            "#underLine": false, 
            "#strikeOut": false 
        }, 
        "Arial": { 
            "replace": "HarmonyOS Sans SC", 
            "#size": 0, 
            "#width": 0, 
            "#weight": 0, 
            "#italic": false, 
            "#underLine": false, 
            "#strikeOut": false 
        } 
    }, 
    "debug": false 
}
