### ISSUE TITLE
请问FontMod64.dll和FontMod32.dll，Win10 64位专业版用哪个？还是两个一起用？

### ISSUE THREAD

**Issue by WrathGluttony** [ysc3839/FontMod#69]
①请问FontMod64.dll和FontMod32.dll，Win10 64位专业版用哪个？还是两个一起用？
② Telegram Desktop 版本：2.7.4-语言包翻译者：聪聪
③FontMod v2.1对Telegram电脑版2.7.4有效吗？（系统是Win10 20H2 64位专业版）
④下载FontMod.dll(是32位还是64位?)，重命名为winmm.dll，放入 Telegram Desktop 的根目录内，最后重启一下客户端即可生效,就这么简单地操作吗?

**Comment by ysc3839** [comment]
1. 需要根据目标应用程序是32位还是64位来选择。
2, 3. 没记错的话 Telegram 官方版本还是32位的，需要使用 FontMod32.dll。
4. 差不多是的，还需要根据自己需求修改 `FontMod.yaml` 配置字体。

**Comment by WrathGluttony** [comment]
> 1. 需要根据目标应用程序是32位还是64位来选择。
> 2. 没记错的话 Telegram 官方版本还是32位的，需要使用 FontMod32.dll。
> 3. 差不多是的，还需要根据自己需求修改 `FontMod.yaml` 配置字体。

①谢谢作者的回复
②FontMod32.dll和FontMod64.dll拷贝后均重命名为winmm.dll
③FontMod32.dll和FontMod64.dll我分别拷贝到C:\Users\Pure\AppData\Roaming\Telegram Desktop试了，没有自动生成FontMod.yaml文件
④FontMod32.dll和FontMod64.dll我分别拷贝到C:\Program Files\Telegram Desktop试了，也是没有自动生成FontMod.yaml文件
⑤我用的是FontMod v2.1里的FontMod32.dll和FontMod64.dll，分别试，两个文件夹也分别试，都不自动生成FontMod.yaml文件

**Comment by ysc3839** [comment]
我去 Telegram 官网看了下，已经有64位的版本了。下载安装后，把 `FontMod64.dll` 改名为 `version.dll` 使用是没问题的。
如果 `winmm.dll` 无效的话可以试试 `version.dll`。

**Comment by WrathGluttony** [comment]
> 我去 Telegram 官网看了下，已经有64位的版本了。下载安装后，把 `FontMod64.dll` 改名为 `version.dll` 使用是没问题的。
> 如果 `winmm.dll` 无效的话可以试试 `version.dll`。

①FontMod64.dll和FontMod32.dll我都改为version.dll，然后分别放在“C:\Program Files\Telegram Desktop”和“C:\Users\Pure\AppData\Roaming\Telegram Desktop”这两个路径里，都没有效果，在上述两个路径里都没有生成“FontMod.yaml”这个文件。
②只在FontMod32.dll改为version.dll，然后放在“C:\Program Files\Telegram Desktop”这个路径里才产生1个错误提示，错误提示的截图如下(其它情况下没有任何提示，就这种情况下有1个错误提示)：
![image](https://user-images.githubusercontent.com/50478981/120907764-d6702580-c696-11eb-8f59-bd285593575d.png)

**Comment by Youxikong** [comment]
fontmod加载成功了，但是没有Fontmod.yaml所以出错了，原本会创建一个默认的fontmod.yaml文件，但是由于telegram的安装路径当前用户没有读写权限，telegram又不是以管理员权限创建的，所以也无法创建默认的fontmod.yaml文件。

以管理员权限启动telegram一次就可以了。
