### ISSUE TITLE
TG Desktop 2.8.5 Beta 不允许 DLL 注入了

### ISSUE THREAD

**Issue by doio** [ysc3839/FontMod#70]
https://github.com/telegramdesktop/tdesktop/commit/5b2db4112fc4d5c9759685bb457ec0106b3bba1a

哎，我说怎么突然用不了了，yaml 也不起作用

中文字体又变得好难看，这下还没办法改了。

**Comment by ysc3839** [comment]
这种情况没法解决，可以考虑用第三方工具注入 DLL。

**Comment by tty7tyil** [comment]
防撤回插件那边说
> Fixes are in progress.
是否有可能换用其它实现方式？

**Comment by ysc3839** [comment]
如果你在使用微软商店的 Telegram ([链接](https://www.microsoft.com/store/productId/9NZTWSQNTD0S))，可以试试我的项目 [AppXLauncher](https://github.com/ysc3839/AppXLauncher)。
在[这里](https://github.com/ysc3839/AppXLauncher/actions/runs/1042583200)下载 exe，把 `FontMod64.dll` 放在 exe 同目录下，然后创建 `AppXLauncher.json` 文件并写入以下内容：
```
{
	"PackageFamilyName": "TelegramMessengerLLP.TelegramDesktop_t4vj0pshhgkwm",
	"AppId": "Telegram.TelegramDesktop.Store",
	"InjectDll": "FontMod64.dll",
	"Persistent": true,
	"KillRunning": false
}
```
当 `Persistent` 开启时，在首次运行 AppXLauncher.exe 之后，你可以直接在开始菜单中打开 Telegram，不需要再打开 AppXLauncher.exe。
注意上述文件不能移动或删除。如果你移动了之后打不开 Telegram，或者想卸载，把 `Persistent` 改为 false 后运行一次 AppXLauncher.exe 即可。

**Comment by Rongronggg9** [comment]
有一个非官方的 Telegram Desktop 客户端叫 64Gram (以前叫 Telegram Desktop x64)，提供了 Windows 64bit 的编译并有一些增强功能，包括[特别放行了 fontmod dll 的加载](https://github.com/TDesktop-x64/tdesktop/commit/31d6730c1e58c710e1cb3196c58ae468ce8e2a58)。

**Comment by zlhdd108** [comment]
> 如果你在使用微软商店的 Telegram ([链接](https://www.microsoft.com/store/productId/9NZTWSQNTD0S))，可以试试我的项目 [AppXLauncher](https://github.com/ysc3839/AppXLauncher)。 在[这里](https://github.com/ysc3839/AppXLauncher/actions/runs/1042583200)下载 exe，把 `FontMod64.dll` 放在 exe 同目录下，然后创建 `AppXLauncher.json` 文件并写入以下内容：
> 
> ```
> {
> 	"PackageFamilyName": "TelegramMessengerLLP.TelegramDesktop_t4vj0pshhgkwm",
> 	"AppId": "Telegram.TelegramDesktop.Store",
> 	"InjectDll": "FontMod64.dll",
> 	"Persistent": true,
> 	"KillRunning": false
> }
> ```
> 
> 当 `Persistent` 开启时，在首次运行 AppXLauncher.exe 之后，你可以直接在开始菜单中打开 Telegram，不需要再打开 AppXLauncher.exe。 注意上述文件不能移动或删除。如果你移动了之后打不开 Telegram，或者想卸载，把 `Persistent` 改为 false 后运行一次 AppXLauncher.exe 即可。

大佬，这个没办法下载了啊

**Comment by jchwl0527** [comment]
> > 如果你在使用微软商店的 Telegram （[链接](https://www.microsoft.com/store/productId/9NZTWSQNTD0S)），可以试试我的项目[AppXLauncher](https://github.com/ysc3839/AppXLauncher)。在[这里](https://github.com/ysc3839/AppXLauncher/actions/runs/1042583200)下载 exe，把 放在 exe 同目录下，然后创建 文件并写入以下内容：`FontMod64.dll``AppXLauncher.json`
> > ```
> > {
> > 	"PackageFamilyName": "TelegramMessengerLLP.TelegramDesktop_t4vj0pshhgkwm",
> > 	"AppId": "Telegram.TelegramDesktop.Store",
> > 	"InjectDll": "FontMod64.dll",
> > 	"Persistent": true,
> > 	"KillRunning": false
> > }
> > ```
> > 
> > ![](chrome-extension://mdcffelghikdiafnfodjlgllenhlnejl/icons/copy.png)复制到剪切板
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 当 开启时，在首次运行 AppXLauncher.exe 之后，你可以直接在开始菜单中打开 Telegram，不需要再打开 AppXLauncher.exe。注意上述文件不能移动或删除。如果你移动了之后打不开 Telegram，或者想卸载，把 改为 false 后运行一次 AppXLauncher.exe 即可。`Persistent``Persistent`
> 
> 大佬，这个没办法下载了啊

自己Fork下仓库，打开Actions，然后随便创建一个文件就可以编译出来软件了

**Comment by Menci** [comment]
[AppXLauncher.zip](https://github.com/ysc3839/FontMod/files/15285019/AppXLauncher.zip)

Prebuilt AppXLauncher binaries by CI for those who don't want to fork and trigger CI themselves.
