### ISSUE TITLE
用在最新telegram上不起作用

### ISSUE THREAD

**Issue by aglent** [ysc3839/FontMod#74]
官网下了64位便携版 FontMod64.dll改名为winmm.dll或version.dll 运行时都是没有反应 不会生成FontMod.yaml 手动建一个也没有效果
不知道如何正确配置？

**Comment by ysc3839** [comment]
可能是 #70 所述的问题，可以参考[这个方案](https://github.com/ysc3839/FontMod/issues/70#issuecomment-882069692)。

**Comment by telanxrays** [comment]
2.8.11別下了, 現在改不了字體, 我自動升級後就廢了, 怎麽改配置都沒用. 回滾到2.8又好了, 一樣的dll一樣的配置文件內容, 所以肯定是版本問題.
我的配置文件如下(部分):
fonts:
  微软雅黑: &zh-cn-font # Chinese (Simplified) fallback font
    replace: Microsoft Jhenghei
    <<: *style

**Comment by aglent** [comment]
> 
> 
> 2.8.11別下了, 現在改不了字體, 我自動升級後就廢了, 怎麽改配置都沒用. 回滾到2.8又好了, 一樣的dll一樣的配置文件內容, 所以肯定是版本問題.
> 我的配置文件如下(部分):
> fonts:
> 微软雅黑: &zh-cn-font # Chinese (Simplified) fallback font
> replace: Microsoft Jhenghei
> <<: *style

老版本TG能发我一份吗？谢谢
jaleo.fu@gmail.com

**Comment by telanxrays** [comment]
> > 2.8.11別下了, 現在改不了字體, 我自動升級後就廢了, 怎麽改配置都沒用. 回滾到2.8又好了, 一樣的dll一樣的配置文件內容, 所以肯定是版本問題.
> > 我的配置文件如下(部分):
> > fonts:
> > 微软雅黑: &zh-cn-font # Chinese (Simplified) fallback font
> > replace: Microsoft Jhenghei
> > <<: *style
> 
> 老版本TG能发我一份吗？谢谢
> [jaleo.fu@gmail.com](mailto:jaleo.fu@gmail.com)

telegram的github下載庫里有歷史提交版本的, 點一下右側的Releases進去就看到了.
不過奇怪的是這軟件不知道為什麽我回滾它又給我升級回來, 弄了好多次, 確定已經手動關了升級功能, 還是一樣自動升級, 真是氣死我了. 誰知道為什麽會這樣? 煩請告知, 謝謝.

**Comment by telanxrays** [comment]
另外大佬們誰知道新版怎麽改字體啊??? 真心求教, 還有這項目還有人維護嗎? 好久沒升級了, 以後要是改不了字體用起來好難受啊!!!
