### ISSUE TITLE
 [Request] Enable GitHub Discussions for sharing experiences and working examples

### ISSUE THREAD

**Issue by TTTPOB** [ysc3839/FontMod#83]
I appreciate your work on the fontmod project. I'd like to suggest enabling GitHub Discussions for this repository. It would provide a space for users to share their successful experiences, discuss use cases, and exchange working examples. This would make it easier for users to find relevant information and encourage community engagement.
For example I want to let other people know this little mod work for fusion 360, which do not have a font setting option. if discussion is here I can post my working example there.

**Comment by ysc3839** [comment]
Opened.
